export interface Lesson {
  id: string
  title: string
  duration: string
  description: string
  type: "video" | "document" | "exercise"
  pdfUrl: string
  content?: string
}

export interface Subject {
  id: string
  name: string
  description: string
  lessons: Lesson[]
}

export interface Section {
  id: string
  name: string
  color: string
  icon: string
  subjects: Subject[]
}

const lessonsData: Record<string, Section> = {
  maths: {
    id: "maths",
    name: "Mathématiques",
    color: "from-blue-500 to-blue-600",
    icon: "∑",
    subjects: [
      {
        id: "algebra",
        name: "Algèbre",
        description: "Équations, inéquations et polynômes",
        lessons: [
          {
            id: "l1",
            title: "Introduction aux équations linéaires",
            duration: "15 min",
            description: "Comprendre les bases des équations",
            type: "video",
            pdfUrl: "https://example.com/maths/algebra/l1.pdf",
          },
          {
            id: "l2",
            title: "Résoudre des équations à une variable",
            duration: "20 min",
            description: "Techniques de résolution",
            type: "video",
            pdfUrl: "https://example.com/maths/algebra/l2.pdf",
          },
          {
            id: "l3",
            title: "Exercices d'équations",
            duration: "30 min",
            description: "Pratiquez vos compétences",
            type: "exercise",
            pdfUrl: "https://example.com/maths/algebra/l3.pdf",
          },
          {
            id: "l4",
            title: "Polynômes et factorisation",
            duration: "25 min",
            description: "Concepts avancés",
            type: "document",
            pdfUrl: "https://example.com/maths/algebra/l4.pdf",
          },
          {
            id: "l5",
            title: "Équations quadratiques",
            duration: "22 min",
            description: "Formule et discriminant",
            type: "video",
            pdfUrl: "https://example.com/maths/algebra/l5.pdf",
          },
          {
            id: "l6",
            title: "Inéquations linéaires",
            duration: "18 min",
            description: "Résoudre et représenter",
            type: "document",
            pdfUrl: "https://example.com/maths/algebra/l6.pdf",
          },
        ],
      },
      {
        id: "geometry",
        name: "Géométrie",
        description: "Formes, angles et transformations",
        lessons: [
          {
            id: "l1",
            title: "Formes géométriques de base",
            duration: "15 min",
            description: "Points, lignes et angles",
            type: "video",
            pdfUrl: "https://example.com/maths/geometry/l1.pdf",
          },
          {
            id: "l2",
            title: "Triangles et propriétés",
            duration: "20 min",
            description: "Classification et théorèmes",
            type: "video",
            pdfUrl: "https://example.com/maths/geometry/l2.pdf",
          },
          {
            id: "l3",
            title: "Cercles et circonférence",
            duration: "18 min",
            description: "Géométrie circulaire",
            type: "document",
            pdfUrl: "https://example.com/maths/geometry/l3.pdf",
          },
          {
            id: "l4",
            title: "Problèmes de géométrie",
            duration: "40 min",
            description: "Exercices pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/maths/geometry/l4.pdf",
          },
          {
            id: "l5",
            title: "Symétrie et transformations",
            duration: "20 min",
            description: "Rotations et réflexions",
            type: "video",
            pdfUrl: "https://example.com/maths/geometry/l5.pdf",
          },
          {
            id: "l6",
            title: "Théorème de Pythagore",
            duration: "16 min",
            description: "Application et preuves",
            type: "document",
            pdfUrl: "https://example.com/maths/geometry/l6.pdf",
          },
        ],
      },
      {
        id: "calculus",
        name: "Calcul",
        description: "Dérivées, intégrales et limites",
        lessons: [
          {
            id: "l1",
            title: "Concept de limite",
            duration: "20 min",
            description: "Fondamentaux du calcul",
            type: "video",
            pdfUrl: "https://example.com/maths/calculus/l1.pdf",
          },
          {
            id: "l2",
            title: "Dérivées et taux de changement",
            duration: "25 min",
            description: "Introduction aux dérivées",
            type: "video",
            pdfUrl: "https://example.com/maths/calculus/l2.pdf",
          },
          {
            id: "l3",
            title: "Règles de dérivation",
            duration: "22 min",
            description: "Chaîne, produit et quotient",
            type: "document",
            pdfUrl: "https://example.com/maths/calculus/l3.pdf",
          },
          {
            id: "l4",
            title: "Intégrales indéfinies",
            duration: "23 min",
            description: "Antidérivées",
            type: "video",
            pdfUrl: "https://example.com/maths/calculus/l4.pdf",
          },
          {
            id: "l5",
            title: "Exercices de calcul",
            duration: "45 min",
            description: "Problèmes pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/maths/calculus/l5.pdf",
          },
        ],
      },
      {
        id: "statistics",
        name: "Statistiques",
        description: "Données, probabilités et analyse",
        lessons: [
          {
            id: "l1",
            title: "Collecte et organisation de données",
            duration: "18 min",
            description: "Méthodes et types de données",
            type: "video",
            pdfUrl: "https://example.com/maths/statistics/l1.pdf",
          },
          {
            id: "l2",
            title: "Moyenne, médiane et mode",
            duration: "16 min",
            description: "Mesures de tendance centrale",
            type: "video",
            pdfUrl: "https://example.com/maths/statistics/l2.pdf",
          },
          {
            id: "l3",
            title: "Probabilité de base",
            duration: "22 min",
            description: "Événements et calculs",
            type: "document",
            pdfUrl: "https://example.com/maths/statistics/l3.pdf",
          },
          {
            id: "l4",
            title: "Distributions de probabilité",
            duration: "28 min",
            description: "Normale et binomiale",
            type: "video",
            pdfUrl: "https://example.com/maths/statistics/l4.pdf",
          },
          {
            id: "l5",
            title: "Tests statistiques",
            duration: "35 min",
            description: "Hypothèses et analyse",
            type: "exercise",
            pdfUrl: "https://example.com/maths/statistics/l5.pdf",
          },
        ],
      },
    ],
  },
  science: {
    id: "science",
    name: "Sciences",
    color: "from-green-500 to-green-600",
    icon: "⚗",
    subjects: [
      {
        id: "physics",
        name: "Physique",
        description: "Mécanique, électricité et optique",
        lessons: [
          {
            id: "l1",
            title: "Lois du mouvement de Newton",
            duration: "22 min",
            description: "Force et accélération",
            type: "video",
            pdfUrl: "https://example.com/science/physics/l1.pdf",
          },
          {
            id: "l2",
            title: "Énergie et travail",
            duration: "25 min",
            description: "Conservation d'énergie",
            type: "video",
            pdfUrl: "https://example.com/science/physics/l2.pdf",
          },
          {
            id: "l3",
            title: "Électricité et magnétisme",
            duration: "30 min",
            description: "Champs et circuits",
            type: "document",
            pdfUrl: "https://example.com/science/physics/l3.pdf",
          },
          {
            id: "l4",
            title: "Optique et lumière",
            duration: "24 min",
            description: "Réfraction et réflexion",
            type: "video",
            pdfUrl: "https://example.com/science/physics/l4.pdf",
          },
          {
            id: "l5",
            title: "Expériences de physique",
            duration: "45 min",
            description: "Apprentissage pratique",
            type: "exercise",
            pdfUrl: "https://example.com/science/physics/l5.pdf",
          },
        ],
      },
      {
        id: "chemistry",
        name: "Chimie",
        description: "Réactions, molécules et éléments",
        lessons: [
          {
            id: "l1",
            title: "Structure atomique",
            duration: "18 min",
            description: "Atomes et électrons",
            type: "video",
            pdfUrl: "https://example.com/science/chemistry/l1.pdf",
          },
          {
            id: "l2",
            title: "Réactions chimiques",
            duration: "20 min",
            description: "Équilibrer les équations",
            type: "video",
            pdfUrl: "https://example.com/science/chemistry/l2.pdf",
          },
          {
            id: "l3",
            title: "La table périodique",
            duration: "25 min",
            description: "Éléments et propriétés",
            type: "document",
            pdfUrl: "https://example.com/science/chemistry/l3.pdf",
          },
          {
            id: "l4",
            title: "Liaisons chimiques",
            duration: "21 min",
            description: "Covalente, ionique et métallique",
            type: "video",
            pdfUrl: "https://example.com/science/chemistry/l4.pdf",
          },
          {
            id: "l5",
            title: "Laboratoire virtuel",
            duration: "50 min",
            description: "Simuler des réactions",
            type: "exercise",
            pdfUrl: "https://example.com/science/chemistry/l5.pdf",
          },
          {
            id: "l6",
            title: "Acides et bases",
            duration: "19 min",
            description: "pH et neutralisation",
            type: "document",
            pdfUrl: "https://example.com/science/chemistry/l6.pdf",
          },
        ],
      },
      {
        id: "biology",
        name: "Biologie",
        description: "Cellules, génétique et écologie",
        lessons: [
          {
            id: "l1",
            title: "Structure cellulaire",
            duration: "20 min",
            description: "Organelles et fonctions",
            type: "video",
            pdfUrl: "https://example.com/science/biology/l1.pdf",
          },
          {
            id: "l2",
            title: "Division cellulaire",
            duration: "22 min",
            description: "Mitose et méiose",
            type: "video",
            pdfUrl: "https://example.com/science/biology/l2.pdf",
          },
          {
            id: "l3",
            title: "Génétique de Mendel",
            duration: "25 min",
            description: "Hérédité et traits",
            type: "document",
            pdfUrl: "https://example.com/science/biology/l3.pdf",
          },
          {
            id: "l4",
            title: "ADN et protéines",
            duration: "28 min",
            description: "Code génétique",
            type: "video",
            pdfUrl: "https://example.com/science/biology/l4.pdf",
          },
          {
            id: "l5",
            title: "Écosystèmes",
            duration: "23 min",
            description: "Chaînes alimentaires",
            type: "video",
            pdfUrl: "https://example.com/science/biology/l5.pdf",
          },
          {
            id: "l6",
            title: "Exercices de biologie",
            duration: "40 min",
            description: "Pratiquez les concepts",
            type: "exercise",
            pdfUrl: "https://example.com/science/biology/l6.pdf",
          },
        ],
      },
      {
        id: "earth-science",
        name: "Sciences de la Terre",
        description: "Géologie, météorologie et océans",
        lessons: [
          {
            id: "l1",
            title: "Tectonique des plaques",
            duration: "24 min",
            description: "Mouvement et tremblements",
            type: "video",
            pdfUrl: "https://example.com/science/earth-science/l1.pdf",
          },
          {
            id: "l2",
            title: "Minéraux et roches",
            duration: "20 min",
            description: "Classification et formation",
            type: "document",
            pdfUrl: "https://example.com/science/earth-science/l2.pdf",
          },
          {
            id: "l3",
            title: "Météorologie de base",
            duration: "22 min",
            description: "Systèmes météorologiques",
            type: "video",
            pdfUrl: "https://example.com/science/earth-science/l3.pdf",
          },
          {
            id: "l4",
            title: "Océans et courants",
            duration: "21 min",
            description: "Circulation océanique",
            type: "video",
            pdfUrl: "https://example.com/science/earth-science/l4.pdf",
          },
          {
            id: "l5",
            title: "Changement climatique",
            duration: "27 min",
            description: "Causes et conséquences",
            type: "document",
            pdfUrl: "https://example.com/science/earth-science/l5.pdf",
          },
        ],
      },
    ],
  },
  informatique: {
    id: "informatique",
    name: "Informatique",
    color: "from-purple-500 to-purple-600",
    icon: "💻",
    subjects: [
      {
        id: "programming",
        name: "Programmation",
        description: "Python, JavaScript et algorithmes",
        lessons: [
          {
            id: "l1",
            title: "Fondamentaux Python",
            duration: "25 min",
            description: "Variables et types",
            type: "video",
            pdfUrl: "https://example.com/informatique/programming/l1.pdf",
          },
          {
            id: "l2",
            title: "Boucles et conditions",
            duration: "28 min",
            description: "Contrôle de flux",
            type: "video",
            pdfUrl: "https://example.com/informatique/programming/l2.pdf",
          },
          {
            id: "l3",
            title: "Fonctions en Python",
            duration: "22 min",
            description: "Définition et utilisation",
            type: "document",
            pdfUrl: "https://example.com/informatique/programming/l3.pdf",
          },
          {
            id: "l4",
            title: "Introduction à JavaScript",
            duration: "26 min",
            description: "Syntaxe de base",
            type: "video",
            pdfUrl: "https://example.com/informatique/programming/l4.pdf",
          },
          {
            id: "l5",
            title: "Algorithmes et structures de données",
            duration: "35 min",
            description: "Listes et dictionnaires",
            type: "document",
            pdfUrl: "https://example.com/informatique/programming/l5.pdf",
          },
          {
            id: "l6",
            title: "Codage pratique",
            duration: "60 min",
            description: "Projets et exercices",
            type: "exercise",
            pdfUrl: "https://example.com/informatique/programming/l6.pdf",
          },
        ],
      },
      {
        id: "databases",
        name: "Bases de Données",
        description: "SQL, modèles et requêtes",
        lessons: [
          {
            id: "l1",
            title: "Modèle de données relationnel",
            duration: "20 min",
            description: "Schéma et tables",
            type: "video",
            pdfUrl: "https://example.com/informatique/databases/l1.pdf",
          },
          {
            id: "l2",
            title: "SQL select et where",
            duration: "22 min",
            description: "Requêtes de base",
            type: "video",
            pdfUrl: "https://example.com/informatique/databases/l2.pdf",
          },
          {
            id: "l3",
            title: "Jointures SQL",
            duration: "25 min",
            description: "Inner et outer joins",
            type: "document",
            pdfUrl: "https://example.com/informatique/databases/l3.pdf",
          },
          {
            id: "l4",
            title: "Agrégation et groupage",
            duration: "21 min",
            description: "COUNT, SUM et GROUP BY",
            type: "video",
            pdfUrl: "https://example.com/informatique/databases/l4.pdf",
          },
          {
            id: "l5",
            title: "Exercices SQL",
            duration: "50 min",
            description: "Requêtes pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/informatique/databases/l5.pdf",
          },
        ],
      },
      {
        id: "networks",
        name: "Réseaux",
        description: "Internet, protocoles et sécurité",
        lessons: [
          {
            id: "l1",
            title: "Fondamentaux réseau",
            duration: "23 min",
            description: "Protocoles et adresses",
            type: "video",
            pdfUrl: "https://example.com/informatique/networks/l1.pdf",
          },
          {
            id: "l2",
            title: "TCP/IP",
            duration: "26 min",
            description: "Modèle OSI",
            type: "video",
            pdfUrl: "https://example.com/informatique/networks/l2.pdf",
          },
          {
            id: "l3",
            title: "DNS et HTTP",
            duration: "20 min",
            description: "Services Internet",
            type: "document",
            pdfUrl: "https://example.com/informatique/networks/l3.pdf",
          },
          {
            id: "l4",
            title: "Sécurité réseau",
            duration: "28 min",
            description: "Authentification et chiffrement",
            type: "video",
            pdfUrl: "https://example.com/informatique/networks/l4.pdf",
          },
          {
            id: "l5",
            title: "Configuration réseau",
            duration: "45 min",
            description: "Travaux pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/informatique/networks/l5.pdf",
          },
        ],
      },
      {
        id: "web-dev",
        name: "Développement Web",
        description: "HTML, CSS et frameworks",
        lessons: [
          {
            id: "l1",
            title: "HTML de base",
            duration: "20 min",
            description: "Structure et balises",
            type: "video",
            pdfUrl: "https://example.com/informatique/web-dev/l1.pdf",
          },
          {
            id: "l2",
            title: "CSS et mise en page",
            duration: "25 min",
            description: "Flexbox et Grid",
            type: "video",
            pdfUrl: "https://example.com/informatique/web-dev/l2.pdf",
          },
          {
            id: "l3",
            title: "JavaScript interactif",
            duration: "28 min",
            description: "DOM et événements",
            type: "document",
            pdfUrl: "https://example.com/informatique/web-dev/l3.pdf",
          },
          {
            id: "l4",
            title: "React et composants",
            duration: "30 min",
            description: "State et props",
            type: "video",
            pdfUrl: "https://example.com/informatique/web-dev/l4.pdf",
          },
          {
            id: "l5",
            title: "Projet web complet",
            duration: "90 min",
            description: "Construire une application",
            type: "exercise",
            pdfUrl: "https://example.com/informatique/web-dev/l5.pdf",
          },
        ],
      },
    ],
  },
  sport: {
    id: "sport",
    name: "Éducation Physique",
    color: "from-orange-500 to-orange-600",
    icon: "⚽",
    subjects: [
      {
        id: "athletics",
        name: "Athlétisme",
        description: "Course, saut et lancer",
        lessons: [
          {
            id: "l1",
            title: "Techniques de course",
            duration: "20 min",
            description: "Foulée et respiration",
            type: "video",
            pdfUrl: "https://example.com/sport/athletics/l1.pdf",
          },
          {
            id: "l2",
            title: "Entraînement d'endurance",
            duration: "25 min",
            description: "Cardio et vitesse",
            type: "document",
            pdfUrl: "https://example.com/sport/athletics/l2.pdf",
          },
          {
            id: "l3",
            title: "Technique de saut",
            duration: "18 min",
            description: "Hauteur et longueur",
            type: "video",
            pdfUrl: "https://example.com/sport/athletics/l3.pdf",
          },
          {
            id: "l4",
            title: "Lancer : bases",
            duration: "22 min",
            description: "Poids et javelot",
            type: "video",
            pdfUrl: "https://example.com/sport/athletics/l4.pdf",
          },
          {
            id: "l5",
            title: "Entraînement athlétique",
            duration: "40 min",
            description: "Routines pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/sport/athletics/l5.pdf",
          },
        ],
      },
      {
        id: "team-sports",
        name: "Sports Collectifs",
        description: "Football, basket et volley",
        lessons: [
          {
            id: "l1",
            title: "Règles du football",
            duration: "20 min",
            description: "Jeu et tactique",
            type: "video",
            pdfUrl: "https://example.com/sport/team-sports/l1.pdf",
          },
          {
            id: "l2",
            title: "Techniques de basket",
            duration: "22 min",
            description: "Dribble et tir",
            type: "video",
            pdfUrl: "https://example.com/sport/team-sports/l2.pdf",
          },
          {
            id: "l3",
            title: "Volley-ball : fondamentaux",
            duration: "18 min",
            description: "Passe et smash",
            type: "document",
            pdfUrl: "https://example.com/sport/team-sports/l3.pdf",
          },
          {
            id: "l4",
            title: "Stratégies d'équipe",
            duration: "25 min",
            description: "Formation et tactique",
            type: "video",
            pdfUrl: "https://example.com/sport/team-sports/l4.pdf",
          },
          {
            id: "l5",
            title: "Jeu en équipe",
            duration: "50 min",
            description: "Matchs pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/sport/team-sports/l5.pdf",
          },
        ],
      },
      {
        id: "gymnastics",
        name: "Gymnastique",
        description: "Mouvement, équilibre et flexibilité",
        lessons: [
          {
            id: "l1",
            title: "Échauffement et étirements",
            duration: "18 min",
            description: "Préparation du corps",
            type: "video",
            pdfUrl: "https://example.com/sport/gymnastics/l1.pdf",
          },
          {
            id: "l2",
            title: "Équilibre et coordination",
            duration: "20 min",
            description: "Contrôle du corps",
            type: "video",
            pdfUrl: "https://example.com/sport/gymnastics/l2.pdf",
          },
          {
            id: "l3",
            title: "Flexibilité et mobilité",
            duration: "22 min",
            description: "Ampleur de mouvement",
            type: "document",
            pdfUrl: "https://example.com/sport/gymnastics/l3.pdf",
          },
          {
            id: "l4",
            title: "Éléments de base",
            duration: "25 min",
            description: "Roulades et loopings",
            type: "video",
            pdfUrl: "https://example.com/sport/gymnastics/l4.pdf",
          },
          {
            id: "l5",
            title: "Séance de gymnase",
            duration: "45 min",
            description: "Pratique guidée",
            type: "exercise",
            pdfUrl: "https://example.com/sport/gymnastics/l5.pdf",
          },
        ],
      },
      {
        id: "wellness",
        name: "Bien-être",
        description: "Santé, nutrition et fitness",
        lessons: [
          {
            id: "l1",
            title: "Nutrition de base",
            duration: "20 min",
            description: "Groupes alimentaires",
            type: "video",
            pdfUrl: "https://example.com/sport/wellness/l1.pdf",
          },
          {
            id: "l2",
            title: "Fitness et force",
            duration: "25 min",
            description: "Entraînement musculaire",
            type: "video",
            pdfUrl: "https://example.com/sport/wellness/l2.pdf",
          },
          {
            id: "l3",
            title: "Santé mentale",
            duration: "22 min",
            description: "Bien-être holistique",
            type: "document",
            pdfUrl: "https://example.com/sport/wellness/l3.pdf",
          },
          {
            id: "l4",
            title: "Sommeil et récupération",
            duration: "18 min",
            description: "Repos optimal",
            type: "video",
            pdfUrl: "https://example.com/sport/wellness/l4.pdf",
          },
          {
            id: "l5",
            title: "Programme fitness personnel",
            duration: "60 min",
            description: "Créer votre plan",
            type: "exercise",
            pdfUrl: "https://example.com/sport/wellness/l5.pdf",
          },
        ],
      },
    ],
  },
  economics: {
    id: "economics",
    name: "Économie & Gestion",
    color: "from-amber-500 to-amber-600",
    icon: "📈",
    subjects: [
      {
        id: "microeconomics",
        name: "Microéconomie",
        description: "Marchés, prix et consommateurs",
        lessons: [
          {
            id: "l1",
            title: "Offre et demande",
            duration: "22 min",
            description: "Équilibre de marché",
            type: "video",
            pdfUrl: "https://example.com/economics/microeconomics/l1.pdf",
          },
          {
            id: "l2",
            title: "Élasticité de prix",
            duration: "20 min",
            description: "Sensibilité au prix",
            type: "video",
            pdfUrl: "https://example.com/economics/microeconomics/l2.pdf",
          },
          {
            id: "l3",
            title: "Comportement du consommateur",
            duration: "25 min",
            description: "Utilité et choix",
            type: "document",
            pdfUrl: "https://example.com/economics/microeconomics/l3.pdf",
          },
          {
            id: "l4",
            title: "Structure du marché",
            duration: "23 min",
            description: "Concurrence et monopole",
            type: "video",
            pdfUrl: "https://example.com/economics/microeconomics/l4.pdf",
          },
          {
            id: "l5",
            title: "Analyse économique",
            duration: "40 min",
            description: "Cas d'études",
            type: "exercise",
            pdfUrl: "https://example.com/economics/microeconomics/l5.pdf",
          },
        ],
      },
      {
        id: "macroeconomics",
        name: "Macroéconomie",
        description: "Inflation, emploi et croissance",
        lessons: [
          {
            id: "l1",
            title: "Produit intérieur brut",
            duration: "24 min",
            description: "Mesure de l'économie",
            type: "video",
            pdfUrl: "https://example.com/economics/macroeconomics/l1.pdf",
          },
          {
            id: "l2",
            title: "Inflation et déflation",
            duration: "22 min",
            description: "Niveaux de prix",
            type: "video",
            pdfUrl: "https://example.com/economics/macroeconomics/l2.pdf",
          },
          {
            id: "l3",
            title: "Emploi et chômage",
            duration: "21 min",
            description: "Marché du travail",
            type: "document",
            pdfUrl: "https://example.com/economics/macroeconomics/l3.pdf",
          },
          {
            id: "l4",
            title: "Croissance économique",
            duration: "25 min",
            description: "Facteurs de croissance",
            type: "video",
            pdfUrl: "https://example.com/economics/macroeconomics/l4.pdf",
          },
          {
            id: "l5",
            title: "Politique économique",
            duration: "35 min",
            description: "Intervention du gouvernement",
            type: "exercise",
            pdfUrl: "https://example.com/economics/macroeconomics/l5.pdf",
          },
        ],
      },
      {
        id: "business",
        name: "Gestion d'Entreprise",
        description: "Management et stratégie",
        lessons: [
          {
            id: "l1",
            title: "Fondamentaux d'affaires",
            duration: "23 min",
            description: "Types d'entreprises",
            type: "video",
            pdfUrl: "https://example.com/economics/business/l1.pdf",
          },
          {
            id: "l2",
            title: "Gestion stratégique",
            duration: "26 min",
            description: "Planification et vision",
            type: "video",
            pdfUrl: "https://example.com/economics/business/l2.pdf",
          },
          {
            id: "l3",
            title: "Leadership et équipe",
            duration: "22 min",
            description: "Gestion des ressources humaines",
            type: "document",
            pdfUrl: "https://example.com/economics/business/l3.pdf",
          },
          {
            id: "l4",
            title: "Marketing et ventes",
            duration: "25 min",
            description: "Stratégie client",
            type: "video",
            pdfUrl: "https://example.com/economics/business/l4.pdf",
          },
          {
            id: "l5",
            title: "Cas d'entreprise",
            duration: "50 min",
            description: "Analyse pratique",
            type: "exercise",
            pdfUrl: "https://example.com/economics/business/l5.pdf",
          },
        ],
      },
      {
        id: "accounting",
        name: "Comptabilité",
        description: "Bilan, budget et finances",
        lessons: [
          {
            id: "l1",
            title: "Équation comptable",
            duration: "20 min",
            description: "Actif, passif et capitaux",
            type: "video",
            pdfUrl: "https://example.com/economics/accounting/l1.pdf",
          },
          {
            id: "l2",
            title: "Journal et grand livre",
            duration: "23 min",
            description: "Enregistrement des transactions",
            type: "video",
            pdfUrl: "https://example.com/economics/accounting/l2.pdf",
          },
          {
            id: "l3",
            title: "États financiers",
            duration: "25 min",
            description: "Bilan et compte de résultat",
            type: "document",
            pdfUrl: "https://example.com/economics/accounting/l3.pdf",
          },
          {
            id: "l4",
            title: "Analyse financière",
            duration: "24 min",
            description: "Ratios et interprétation",
            type: "video",
            pdfUrl: "https://example.com/economics/accounting/l4.pdf",
          },
          {
            id: "l5",
            title: "Gestion budgétaire",
            duration: "35 min",
            description: "Planification financière",
            type: "exercise",
            pdfUrl: "https://example.com/economics/accounting/l5.pdf",
          },
        ],
      },
    ],
  },
  technique: {
    id: "technique",
    name: "Filières Techniques",
    color: "from-slate-500 to-slate-600",
    icon: "🔧",
    subjects: [
      {
        id: "mechanics",
        name: "Mécanique",
        description: "Machines, moteurs et structures",
        lessons: [
          {
            id: "l1",
            title: "Statique et équilibre",
            duration: "22 min",
            description: "Forces et moments",
            type: "video",
            pdfUrl: "https://example.com/technique/mechanics/l1.pdf",
          },
          {
            id: "l2",
            title: "Cinématique et dynamique",
            duration: "25 min",
            description: "Mouvement et accélération",
            type: "video",
            pdfUrl: "https://example.com/technique/mechanics/l2.pdf",
          },
          {
            id: "l3",
            title: "Systèmes mécaniques",
            duration: "23 min",
            description: "Leviers et poulies",
            type: "document",
            pdfUrl: "https://example.com/technique/mechanics/l3.pdf",
          },
          {
            id: "l4",
            title: "Moteurs et transmissions",
            duration: "26 min",
            description: "Types et efficacité",
            type: "video",
            pdfUrl: "https://example.com/technique/mechanics/l4.pdf",
          },
          {
            id: "l5",
            title: "Conception mécanique",
            duration: "45 min",
            description: "Projets pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/technique/mechanics/l5.pdf",
          },
        ],
      },
      {
        id: "electricity",
        name: "Électricité Appliquée",
        description: "Circuits et installations",
        lessons: [
          {
            id: "l1",
            title: "Courant et tension",
            duration: "20 min",
            description: "Loi d'Ohm",
            type: "video",
            pdfUrl: "https://example.com/technique/electricity/l1.pdf",
          },
          {
            id: "l2",
            title: "Circuits en série et parallèle",
            duration: "22 min",
            description: "Analyse de circuits",
            type: "video",
            pdfUrl: "https://example.com/technique/electricity/l2.pdf",
          },
          {
            id: "l3",
            title: "Puissance électrique",
            duration: "19 min",
            description: "Wattage et efficacité",
            type: "document",
            pdfUrl: "https://example.com/technique/electricity/l3.pdf",
          },
          {
            id: "l4",
            title: "Installations domestiques",
            duration: "24 min",
            description: "Sécurité électrique",
            type: "video",
            pdfUrl: "https://example.com/technique/electricity/l4.pdf",
          },
          {
            id: "l5",
            title: "Laboratoire électricité",
            duration: "50 min",
            description: "Montages pratiques",
            type: "exercise",
            pdfUrl: "https://example.com/technique/electricity/l5.pdf",
          },
        ],
      },
      {
        id: "construction",
        name: "Construction",
        description: "Bâtiment et travaux publics",
        lessons: [
          {
            id: "l1",
            title: "Matériaux de construction",
            duration: "23 min",
            description: "Propriétés et utilisation",
            type: "video",
            pdfUrl: "https://example.com/technique/construction/l1.pdf",
          },
          {
            id: "l2",
            title: "Structures de bâtiment",
            duration: "25 min",
            description: "Charpente et fondations",
            type: "video",
            pdfUrl: "https://example.com/technique/construction/l2.pdf",
          },
          {
            id: "l3",
            title: "Plans et devis",
            duration: "22 min",
            description: "Lecture de plans",
            type: "document",
            pdfUrl: "https://example.com/technique/construction/l3.pdf",
          },
          {
            id: "l4",
            title: "Techniques de construction",
            duration: "26 min",
            description: "Méthodes de travail",
            type: "video",
            pdfUrl: "https://example.com/technique/construction/l4.pdf",
          },
          {
            id: "l5",
            title: "Visite de chantier",
            duration: "60 min",
            description: "Observation pratique",
            type: "exercise",
            pdfUrl: "https://example.com/technique/construction/l5.pdf",
          },
        ],
      },
      {
        id: "automation",
        name: "Automatisation",
        description: "Robotique et contrôle",
        lessons: [
          {
            id: "l1",
            title: "Automates programmables",
            duration: "24 min",
            description: "Introduction aux PLC",
            type: "video",
            pdfUrl: "https://example.com/technique/automation/l1.pdf",
          },
          {
            id: "l2",
            title: "Capteurs et actionneurs",
            duration: "22 min",
            description: "Entrées et sorties",
            type: "video",
            pdfUrl: "https://example.com/technique/automation/l2.pdf",
          },
          {
            id: "l3",
            title: "Programmation ladder",
            duration: "26 min",
            description: "Logique de contrôle",
            type: "document",
            pdfUrl: "https://example.com/technique/automation/l3.pdf",
          },
          {
            id: "l4",
            title: "Robotique de base",
            duration: "25 min",
            description: "Bras et mouvements",
            type: "video",
            pdfUrl: "https://example.com/technique/automation/l4.pdf",
          },
          {
            id: "l5",
            title: "Projets d'automatisation",
            duration: "55 min",
            description: "Programmation pratique",
            type: "exercise",
            pdfUrl: "https://example.com/technique/automation/l5.pdf",
          },
        ],
      },
    ],
  },
}

export function getSections(): Section[] {
  return Object.values(lessonsData)
}

export function getSection(id: string): Section | undefined {
  return lessonsData[id]
}

export function getSubject(sectionId: string, subjectId: string): Subject | undefined {
  return lessonsData[sectionId]?.subjects.find((s) => s.id === subjectId)
}

export function getLesson(sectionId: string, subjectId: string, lessonId: string): Lesson | undefined {
  return lessonsData[sectionId]?.subjects.find((s) => s.id === subjectId)?.lessons.find((l) => l.id === lessonId)
}
